flask-base/app/models/programme.py
from .. import db
from datetime import datetime
from logging import log
from time import time

class Programme(db.Model):
    __tablename__ = 'programmes'
    id = db.Column(db.Integer, primary_key=True)
    segment = db.Column(db.String)
    description = db.Column(db.Text)
    start_time= db.Column(db.DateTime)
    end_time= db.Column(db.DateTime)
    banner = db.Column(db.String, default=None, nullable=True)
    banner_displayed = db.Column(db.Boolean, default=False)
    video = db.Column(db.String)
    event_id = db.Column(db.Integer, db.ForeignKey('events.id'))
    
    created_at = db.Column(db.DateTime, default=db.func.now())
    updated_at = db.Column(db.DateTime, default=db.func.now(), onupdate=db.func.now())

    def __repr__(self):
        return u'<{self.__class__.__name__}: {self.id}>'.format(self=self)

flask-base/app/models/upload.py
from app import db


class Upload(db.Model):
    __tablename__ = 'images'
    id = db.Column(db.Integer, primary_key=True)
    image_filename = db.Column(db.String, default=None, nullable=True)
    image_url = db.Column(db.String, default=None, nullable=True)
    created_at = db.Column(db.DateTime, default=db.func.now())

    def __repr__(self):
        return u'<{self.__class__.__name__}: {self.id}>'.format(self=self)

flask-base/app/blueprints/programme/forms.py
from flask_ckeditor import CKEditorField
from flask_uploads import UploadSet, IMAGES
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import ValidationError
from wtforms.ext.sqlalchemy.fields import QuerySelectField, QuerySelectMultipleField
from wtforms.fields import (
    PasswordField,
    StringField,
    SubmitField,
    SelectField,
    IntegerField,
    DecimalField,
    FloatField,
    FileField,
    BooleanField,
    MultipleFileField,
    TextAreaField
    
)
from wtforms.fields.html5 import EmailField, DateField, DateTimeLocalField
from wtforms.validators import (
    Email,
    EqualTo,
    InputRequired,
    Length,
)
from wtforms.validators import Email, EqualTo, InputRequired, Length, Optional
from wtforms_alchemy import Unique, ModelForm, model_form_factory
from app.models import *


images = UploadSet('images', IMAGES)
BaseModelForm = model_form_factory(FlaskForm)


class VideoForm(FlaskForm):
    video = FileField('Video', validators=[FileRequired()])
    submit = SubmitField('Submit')

class BannerForm(FlaskForm):
    banner = FileField('Banner Image', validators=[FileRequired(), FileAllowed(images, 'Images only!')])
    submit = SubmitField('Submit')

class ProgrammeForm(FlaskForm):
    segment = SelectField(u'Programme Segment', choices=[('Welcome', 'Welcome'), ('Opening', 'Opening'),
                                                         ('Praise', 'Praise'), ('Rhapsody Adults', 'Rhapsody Adults'),
                                                         ('Rhapsody Teens', 'Rhapsody Teens'), ('Rhapsody Kids', 'Rhapsody Kids'),
                                                         ('Promo', 'Promo'), ('Offering', 'Offering'),
                                                         ('Message', 'Message'), ('Closing', 'Closing')])
    title = StringField('Programme Title E.g a wonderful day with the Spirit')
    description = TextAreaField('Write anything people should see on the page or on search engines')
    start_time = DateTimeLocalField('StartDate & Time:', format='%Y-%m-%dT%H:%M')
    end_time = DateTimeLocalField('EndDate & Time:', format='%Y-%m-%dT%H:%M')
    video = FileField('Video', validators=[FileRequired()])
    image = FileField('Welcome banner Image to be displayed', validators=[Optional(), FileAllowed(images, 'Images only!')])
    banner_displayed = BooleanField("Display banner ?")
    image = FileField('Stay tuned banner Image to be displayed', validators=[Optional(), FileAllowed(images, 'Images only!')])
    stay_tuned_banner_displayed = BooleanField("Display stay tuned banner ?")
    login_required = BooleanField("Registration Required ?")

    submit = SubmitField('Submit')

flask-base/app/blueprints/programme/__init__.py
from app.blueprints.programme import errors  # noqa
from app.blueprints.programme.views import * # noqa

flask-base/app/blueprints/programme/views.py
import json
import os
from flask import render_template, request, flash, redirect, url_for, current_app
from flask_login import login_required, current_user
from flask_uploads import UploadSet, IMAGES
from flask_wtf.file import FileAllowed
from werkzeug.utils import secure_filename
from wtforms import Flags

from app import db
from app.blueprints.programme.forms import *
from app.decorators import admin_required
from app.models import *

from flask import Blueprint, render_template

from app.models import EditableHTML

programme = Blueprint('programme', __name__)
images = UploadSet('images', IMAGES)
photos = UploadSet('photos', IMAGES)
media = UploadSet('photos', IMAGES)



#UPLOAD_FOLDER = '/home/ubuntu/FlaskApp/flask-base/app/static/'
#UPLOAD_FOLDER = '/Users/oem/Documents/bucket/ubuntu/FlaskApp/flask-base/app/static/videos'
UPLOAD_FILE=os.getcwd()+'/static/videos'

@programme.app_errorhandler(500)
def internal_server_error(_):
    return render_template('errors/500.html'), 500


@programme.route('/programme/add', methods=['Get', 'POST'])
@programme.route('/add/programme', methods=['Get', 'POST'])
#@login_required
def add_programme():
    form = ProgrammeForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            image_filename = ""
            if request.files['image']:
                image_filename = images.save(request.files['image'])
            video_filename = request.files['video']
            if video_filename.filename != '':
            #if request.files['video']:
                video_filename.save(os.path.join(current_app.config['UPLOADED_FILES_DEST'], video_filename.filename))
     
            appt = Programme(banner=image_filename,
                segment = form.segment.data,
                video = video_filename.filename,
                description = form.description.data,
                start_time = form.start_time.data,
                end_time = form.end_time.data,
                banner_displayed = form.banner_displayed.data,   
                            )
            db.session.add(appt)
            db.session.commit()
            flash('programme {} successfully created'.format(appt.segment), 'success')
            return redirect(url_for('programme.programmes'))
    return render_template('programme/add_programme.html', form=form)


@programme.route('/<int:programme_id>/programme/edit', methods=['GET', 'POST'])
#@login_required
def edit_programme(programme_id):
    org = Organisation.query.get(1)
    settings = Programme.query.filter_by(id=programme_id).first_or_404()
    photo = Programme.query.filter_by(id=programme_id).first_or_404()
    banner = images.url(photo.banner)
    form = ProgrammeForm(obj=settings)
    if request.method == 'POST':
        if form.validate_on_submit():
            image_filename = ""
            if request.files['image']:
                image_filename = images.save(request.files['image'])
            video_filename = request.files['video']
            if video_filename != '':
            #if request.files['video']:
                video_filename.save(video_filename)
     
            appt = Programme(banner=image_filename,
                segment = form.segment.data,
                video = video_filename,
                description = form.description.data,
                start_time = form.start_time.data,
                end_time = form.end_time.data,
                banner_displayed = form.banner_displayed.data,   
                            )
            form.populate_obj(appt)
            db.session.add(appt)
            db.session.commit()
    #if request.method == 'POST' and 'image' in request.files:
       # image = images.save(request.files['image'])
        #form.populate_obj(settings)
        #db.session.add(settings)
        #db.session.commit()
            flash('Data edited!', 'success')
            return redirect(url_for('programme.programmes'))
    else:
        flash('Error! Data was not added.', 'error')
    return render_template('programme/edit_programme.html', form=form, banner=banner)


@programme.route('/programme', defaults={'page': 1}, methods=['GET'])
@programme.route('/programme/<int:page>', methods=['GET'])
#@login_required
#@admin_required
def programmes(page):
    programmes = Programme.query.paginate(page, per_page=100)
    return render_template('programme/browse.html', programmes=programmes)


@programme.route('/programme/<int:programme_id>/_delete', methods=['GET'])
@login_required
@admin_required
def delete_programme(programme_id):
    programme = Programme.query.filter_by(id=programme_id).first()
    db.session.delete(programme)
    db.session.commit()
    flash('Successfully deleted a programme member.', 'success')
    return redirect(url_for('programme.programmes'))

@programme.route('/banner/upload', methods=['GET', 'POST'])
@login_required
def banner_upload():
   # ''' check if banner already exist, if it does, send to homepage. Avoid duplicate upload here'''
    #check_banner_exist = db.session.query(Banner).filter(Banner.organisation_id == Organisation.id).count()
    #if check_banner_exist >= 1:
        #return redirect(url_for('admin.church_dashboard'))
    form = BannerForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            image_filename = images.save(request.files['banner'])
            image_url = images.url(image_filename)
            owner_organisation = db.session.query(Organisation).first()
            banner = Banner(
                image_filename=image_filename,
                image_url=image_url,
                owner_organisation=owner_organisation.org_name,
                organisation_id=owner_organisation.id
            )
            db.session.add(banner)
            db.session.commit()
            flash("Image saved.")
            return redirect(url_for('programme.banners'))
        else:
            flash('ERROR! Banner was not saved.', 'error')
    return render_template('programme/upload.html', form=form)


@programme.route('/banners', defaults={'page': 1}, methods=['GET'])
@programme.route('/banners/<int:page>', methods=['GET'])
@login_required
@admin_required
def banners(page):
    banners = Banner.query.paginate(page, per_page=100)
    banner = Banner.query.first()
    if banner is None:
        return redirect(url_for('programme.banner_upload'))

    return render_template('programme/banner_browse.html', banners=banners, banner=banner)

@programme.route('/banner/<int:banner_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_banner_upload(banner_id):
    banner = Banner.query.filter_by(id=banner_id).first_or_404()
    form = BannerForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            image_filename = images.save(request.files['banner'])
            image_url = images.url(image_filename)
            owner_programme = db.session.query(Organisation).filter_by(user_id=current_user.id).first()
            banner.image_filename=image_filename,
            banner.image_url=image_url,
            banner.owner_programme=owner_organisation.org_name,
            banner.organisation_id=owner_organisation.id
            db.session.add(banner)
            db.session.commit()
            flash("Image saved.")
            return redirect(url_for('programme.banners'))
        else:
            flash('ERROR! Banner was not saved.', 'error')
    return render_template('programme/upload.html', form=form)

@programme.route('/banner/<int:banner_id>/_delete', methods=['GET'])
@login_required
@admin_required
def delete_banner(banner_id):
    banner = Banner.query.filter_by(id=banner_id).first()
    db.session.delete(banner)
    db.session.commit()
    flash('Successfully deleted Banner.', 'success')
    return redirect(url_for('admin.frontend_dashboard'))


@programme.route('/video/upload', methods=['GET', 'POST'])
@login_required
def video_upload():
    form = VideoForm()
    if form.validate_on_submit():
        f = form.video.data
        filename = secure_filename(f.filename)
        #f.save(filename)
        f.save(os.path.join(current_app.config['UPLOADED_FILES_DEST'], filename))
        video=Video(name=f.filename)
        db.session.add(video)
        db.session.commit()
        return 'file uploaded successfully'
    else:
        flash('ERROR! Banner was not saved.', 'error')
    return render_template('programme/video_upload.html', form=form)




##@programme.route('/programme/add', methods=['Get', 'POST'])
##@programme.route('/add/programme', methods=['Get', 'POST'])
###@login_required
##def add_programme():
##    org = Organisation.query.get(1)
##    form = programmeForm()
##
##    if request.method == 'POST' and 'image' in request.files:
##        image = images.save(request.files['image'])
##        appt = programme(image=image,
##                    #owner_programme=org.org_name,
##                    #programme_id=org.id,
##
##                    programme_name = form.programme_name.data,
##                    programme_title = form.programme_title.data,
##                    programme_description = form.programme_description.data
##                          )
##        db.session.add(appt)
##        db.session.commit()
##        flash('programme added!', 'success')
##        return redirect(url_for('programme.programmes'))
##    return render_template('programme/add_programme.html', form=form, org=org)

flask-base/app/templates/programme/add_programme.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}


{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <a class="ui basic compact button" href="{{ url_for('admin.event_dashboard') }}">
                <i class="caret left icon"></i>
                Back to Event Dashboard
            </a>
            <h2 class="ui header">
                Add a programme
                <div class="sub header">Add a new service or event programme</div>
            </h2>

            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-email']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}
            <div class="one fields">
                {{ f.render_form_field(form.segment) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.description) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.image) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.video) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.banner_displayed) }}
            </div>
            <div class="two fields">
                {{ f.render_form_field(form.start_time) }}
                {{ f.render_form_field(form.end_time) }}
            </div>				
            {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
            {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
            {{ f.form_message(flashes['info'], header='Information', class='info') }}
            {{ f.form_message(flashes['success'], header='Success!', class='success') }}

            {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                {{ f.render_form_field(field) }}
            {% endfor %}

            {{ f.end_form() }}

        </div>
    </div>
{% endblock %}

flask-base/app/templates/programme/banner_browse.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="ui stackable grid container">
                        <div class="four wide column">
        </div>
        <div class="twelve wide tablet twelve wide computer centered column">
            <a class="ui basic compact button" href="{{ url_for('admin.event_dashboard') }}">
                <i class="caret left icon"></i>
                Back to Event dashboard
            </a>

			<a class="ui right floated green button" href="{{ url_for('programme.banner_upload') }}">
                <i class="caret right icon"></i>
                	Upload Banner
            </a> 			

            <h2 class="ui header">
               Manage Banner Upload, Edit and Delete
            </h2>
            {# Use overflow-x: scroll so that mobile views don't freak out
             # when the table is too wide #}
            <div style="overflow-x: scroll;">
                <table class="ui searchable sortable unstackable selectable celled table">
                    <thead>
                    <tr>
                        <th>File Name</th>
                       <th>Storage Location (URL)</th>
                        <th>Created At</th>
                       <th>Updated At</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for banner in banners.items | sort(attribute='created_at') %}
                        <tr>

                            <td>{{ banner.image_filename }}</td>
                            <td>{{ banner.image_url }}</td>
                            <td>{{ banner.created_at }}</td>
                            <td>{{ banner.updated_at }}</td>
                            <td>
                                <a class="ui blue left floated button" style="margin-top: 1px" href="{{ url_for('programme.edit_banner_upload', banner_id=banner.id) }}">Edit</a>
                            </td>
                            <td>
                                <a class="ui red left floated button" style="margin-top: 1px"
                                   href="{{ url_for('programme.delete_banner', banner_id=banner.id) }}" onclick="return confirmDeleteBanner('{{ banner.id | tojson }}');" data-content="{{ banner.id }}">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

            <br>
            <br>
            <br>
            <div class="ui centered grid ">
                <div class="ui pagination menu">
                    {% for page in banners.iter_pages() %}
                        {% if page %}
                            {% if page != banners.page %}
                                <a class="item" href="{{ url_for('programme.banners', page=page) }}">
                                    {{ page }}
                                </a>
                            {% else %}
                                <a class="item active">
                                    {{ page }}
                                </a>
                            {% endif %}
                        {% else %}
                            <div class="disabled item">
                                ...
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>


        </div>
        <form method="POST" action="{{ url_for('programme.delete_banner', banner_id=0) }}" id="delete-banner-form">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        </form>
    </div>

{% endblock %}

{% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script>
        function confirmDeleteBanner(banner_id){
            swal({
                title: "Are you sure?",
                text: "Once deleted, you will not be able to recover this banner",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        let form = $("#delete-banner-form");
                        form.attr('action', "{{ url_for('programme.delete_banner', banner_id=0) }}".replace('0',banner_id));
                        form.submit();
                    } else {
                        return false;
                    }
                });
            return false;
        }
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#search-users').keyup(function () {
                var searchText = $(this).val();
                if (searchText.length > 0) {
                    $('tbody td:icontains(' + searchText + ')').addClass('positive');
                    $('td.positive').not(':icontains(' + searchText + ')').removeClass('positive');
                    $('tbody td').not(':icontains(' + searchText + ')').closest('tr').addClass('hidden').hide();
                    $('tr.hidden:icontains(' + searchText + ')').removeClass('hidden').show();
                } else {
                    $('td.positive').removeClass('positive');
                    $('tr.hidden').removeClass('hidden').show();
                }
            });

            $('#select-role').dropdown({
                onChange: function (value, text, $selectedItem) {
                    $('td.user.role:contains(' + value + ')').closest('tr').removeClass('hidden').show();
                    $('td.user.role').not(':contains(' + value + ')').closest('tr').addClass('hidden').hide();
                }
            });
        });
    </script>
{% endblock %}

flask-base/app/templates/programme/browse.html
{% extends 'layouts/base.html' %}

{% block content %}

        <div class="ui container">
            <a class="ui basic compact button" href="{{ url_for('admin.frontend_dashboard') }}">
                <i class="caret left icon"></i>
                Back to Administrator dashboard
            </a>  
 	
		<a class="ui right floated green button" href="{{ url_for('programme.add_programme') }}">
                <i class="caret right icon"></i>
                Add New Programme
            </a> 
            <h2 class="ui header">
               Manage Programmes Added 
                <div class="sub header">
                    View and manage programmes shown on the front landing page.
                </div>
            </h2>

            {# Use overflow-x: scroll so that mobile views don't freak out
             # when the table is too wide #}
            <div style="overflow-x: scroll;">
                <table class="ui searchable sortable unstackable selectable celled table">
                    <thead>
                    <tr>
                        <th>Segment</th>
                        <th>Programme Description</th>
                        <th>Start Time</th>
                        <th>End Time</th>						
                        <th>Video</th>
                        <th>Banner Image</th>
                        <th>Banner Displayed</th>
                        <th class="sorted ascending">Created At</th>
                        <th>Last Update</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for programme in programmes.items | sort(attribute='created_at') %}
                        <tr>

                            <td>{{ programme.segment }}</td>
                            <td>{{ programme.description }}</td>
                            <td>{{ programme.start_time }}</td>
                            <td>{{ programme.end_time }}</td>
                            <td>{{ programme.video }}</td>
                            <td>{{ programme.banner }}</td>
                            <td>{{ programme.banner_displayed }}</td>
                            <td>{{ programme.created_at }}</td>
                            <td>{{ programme.updated_at }}</td>
                            <td>
                                <!--<a class="ui blue left floated button" style="margin-top: 1px" href="{# url_for('programme.edit_programme', programme_id=programme.id) #}">Edit</a>	---->						
							</td>
                            <td>
                                <a class="ui red left floated button" style="margin-top: 1px"
                                   href="/programme/{{programme.id}}/_delete">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

            <br>
            <br>
            <br>
            <div class="ui centered grid ">
                <div class="ui pagination menu">
                    {% for page in programmes.iter_pages() %}
                        {% if page %}
                            {% if page != programmes.page %}
                                <a class="item" href="{{ url_for('programme.programmes', page=page) }}">
                                    {{ page }}
                                </a>
                            {% else %}
                                <a class="item active">
                                    {{ page }}
                                </a>
                            {% endif %}
                        {% else %}
                            <div class="disabled item">
                                ...
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>



        <form method="POST" action="{{ url_for('programme.delete_programme', programme_id=0) }}" id="delete-programme-form">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        </form>
    </div>

{% endblock %}

{% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script>
        function confirmDeleteTeam(programme_id){
            swal({
                title: "Are you sure?",
                text: "Once deleted, you will not be able to recover this programme",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        let form = $("#delete-programme-form");
                        form.attr('action', "{{ url_for('programme.delete_programme', programme_id=0) }}".replace('0',programme_id));
                        form.submit();
                    } else {
                        return false;
                    }
                });
            return false;
        }
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#search-users').keyup(function () {
                var searchText = $(this).val();
                if (searchText.length > 0) {
                    $('tbody td:icontains(' + searchText + ')').addClass('positive');
                    $('td.positive').not(':icontains(' + searchText + ')').removeClass('positive');
                    $('tbody td').not(':icontains(' + searchText + ')').closest('tr').addClass('hidden').hide();
                    $('tr.hidden:icontains(' + searchText + ')').removeClass('hidden').show();
                } else {
                    $('td.positive').removeClass('positive');
                    $('tr.hidden').removeClass('hidden').show();
                }
            });

            $('#select-role').dropdown({
                onChange: function (value, text, $selectedItem) {
                    $('td.user.role:contains(' + value + ')').closest('tr').removeClass('hidden').show();
                    $('td.user.role').not(':contains(' + value + ')').closest('tr').addClass('hidden').hide();
                }
            });
        });
    </script>
{% endblock %}

flask-base/app/templates/programme/edit_programme.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}


{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <a class="ui basic compact button" href="{{ url_for('admin.event_dashboard') }}">
                <i class="caret left icon"></i>
                Back to Event Dashboard
            </a>
            <h2 class="ui header">
                Edit Section Details
                <div class="sub header">Edit details</div>
            </h2>

            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-email']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}
            <div class="one fields">
                {{ f.render_form_field(form.segment) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.description) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.image) }}
            </div>
            <div class="field">
                {# f.render_form_field(form.video) #}
            </div>
            <div class="field">
                {{ f.render_form_field(form.banner_displayed) }}
            </div>
            <div class="two fields">
                {{ f.render_form_field(form.start_time) }}
                {{ f.render_form_field(form.end_time) }}
            </div>	

            {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
            {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
            {{ f.form_message(flashes['info'], header='Information', class='info') }}
            {{ f.form_message(flashes['success'], header='Success!', class='success') }}

            {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                {{ f.render_form_field(field) }}
            {% endfor %}

            {{ f.end_form() }}

        </div>
    </div>
{% endblock %}

flask-base/app/templates/programme/show.html
{% extends 'layouts/base.html' %}



{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">

            <h2 class="ui header">
                Show
                <div class="sub header"><p> Please kindly upload your background banner image. </p>
                </div>
            </h2>
		
			
				<iframe src="/static/videos/{{ video.name }}" allow="autoplay" id="audio" ></iframe>
			


				<iframe src='https://22e4e77c9a2a.ngrok.io/stream ' style='border:0'></iframe>	
				
				<iframe scrolling="auto" allowtransparency="true" name="main" style="width:100%;height:90%;background-image:url('static/images/{{ banner.image_filename}})"> </iframe>



<iframe width="560" height="315" src="http://localhost:5000/stream" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

        </div>
    </div>
{% endblock %}