flask-base/app/models/content.py
from .. import db
from datetime import datetime
from logging import log
from time import time
from sqlalchemy.orm import backref, query_expression
from app.models import Section


class Content(db.Model):
    __tablename__ = 'contents'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String())
    image = db.Column(db.String, default=None, nullable=True)
    video = db.Column(db.String)
    text = db.Column(db.String)
    section_name = db.Column(db.String)
    section_id = db.Column(db.Integer, db.ForeignKey('sections.id', ondelete="CASCADE"),
                           nullable=False)
    description = db.Column(db.String())
    created_at = db.Column(db.DateTime, default=db.func.now())
    updated_at = db.Column(db.DateTime, default=db.func.now(), onupdate=db.func.now())


    def __repr__(self):
        return '<Content %r>' % self.title

flask-base/app/models/section.py
from .. import db
from datetime import datetime
from logging import log
from time import time

class Section(db.Model):
    __tablename__ = 'sections'
    id = db.Column(db.Integer, primary_key=True)
    section_name = db.Column(db.String)
    #section_title = db.Column(db.String)
    #section_description = db.Column(db.String)
    #section_video = db.Column(db.String)
    #image = db.Column(db.String, default=None, nullable=True)
    public = db.Column(db.String)
    contents = db.relationship('Content', backref='section', lazy='dynamic')
   
    created_at = db.Column(db.DateTime, default=db.func.now())
    updated_at = db.Column(db.DateTime, default=db.func.now(), onupdate=db.func.now())

    #def __repr__(self):
        #return u'<{self.__class__.__name__}: {self.id}>'.format(self=self)

    def __repr__(self):
        return '<Section %r>' % self.section_name

    def get_section():
        return  Section.query

flask-base/app/blueprints/section/forms.py
from flask_ckeditor import CKEditorField
from flask_uploads import UploadSet, IMAGES
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import ValidationError
from wtforms.ext.sqlalchemy.fields import QuerySelectField, QuerySelectMultipleField
from wtforms.fields import (
    PasswordField,
    StringField,
    SubmitField,
    SelectField,
    IntegerField,
    DecimalField,
    FloatField,
    FileField,
    BooleanField,
    MultipleFileField,
    TextAreaField
)
from wtforms.fields.html5 import EmailField
from wtforms.validators import (
    Email,
    EqualTo,
    InputRequired,
    Length,
)
from wtforms.validators import Email, EqualTo, InputRequired, Length, Optional
from wtforms_alchemy import Unique, ModelForm, model_form_factory
from app.models import *



images = UploadSet('images', IMAGES)
BaseModelForm = model_form_factory(FlaskForm)

def get_section():
    yield from Section.query

class SectionForm(FlaskForm):
    public = SelectField(u'Make section name public on navigation bar?', choices=[('Yes', 'Yes'), ('No', 'No')])
    section_name = SelectField(u'Section Name', choices=[('jumbotron', 'Marketing Header'), ('Portfolio', 'Portfolio'),
                                                         ('Services', 'Services'), ('about us', 'About Us'),
                                                         ('Testimonials', 'Testimonials'), ('footer', 'footer'),
                                                         ('Pricing', 'Pricing'), ('call2action', 'Call to action'),
                                                         ('Team', 'Team'), ('Faq', 'Faq'),
                                                         ('Features', 'Features')])
    #section_title = StringField('Section Title E.g Portfolio or About Us or Slogan')
    #section_description = StringField('E.g Find out what our customers say about us')
    #section_video = StringField('Link to the video E.g https://youtu.be/3iIviz54lKA')
    #image = FileField('Image', validators=[Optional(), FileAllowed(images, 'Images only!')])
    submit = SubmitField('Submit')



class ContentForm(FlaskForm):
    #sections = QuerySelectMultipleField(
       # 'Section Name',
       # validators=[InputRequired()],
        #get_label='section_name',
        #query_factory=get_section)
    section_name = StringField('Section Name')
    title = StringField('Title E.g We are the best in town')
    text = StringField('Text E.g Watch Video')
    video = StringField('Link to the video E.g https://youtu.be/3iIviz54lKA')
    #image = FileField(' Image', validators=[Optional(), FileAllowed(images, 'Images only!')])
    description = TextAreaField('Description', [Optional()])
    submit = SubmitField('Submit')    

flask-base/app/blueprints/section/__init__.py
from app.blueprints.section import errors  # noqa
from app.blueprints.section.views import * # noqa

flask-base/app/blueprints/section/views.py
import json

from flask import render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from flask_uploads import UploadSet, IMAGES
from flask_wtf.file import FileAllowed
from wtforms import Flags

from app import db
from app.blueprints.section.forms import SectionForm, ContentForm
from app.decorators import admin_required
from app.models import *
from werkzeug.utils import secure_filename
from sqlalchemy import distinct, func


from flask import Blueprint, render_template

from app.models import EditableHTML

section = Blueprint('section', __name__)
images = UploadSet('images', IMAGES)
photos = UploadSet('photos', IMAGES)


@section.app_errorhandler(500)
def internal_server_error(_):
    return render_template('errors/500.html'), 500


@section.route('/section/add', methods=['Get', 'POST'])
@section.route('/add/section', methods=['Get', 'POST'])
#@login_required
def add_section():
    org = Organisation.query.get(1)

    #section_name = db.session.query(func.count(Section.id)).\
        #group_by(Section.section_name)
    section_name = db.session.query(func.count(Section.id)).\
        group_by(Section.section_name)#.first()
    
    
    if section_name >=1 :
        flash('Section {} already exist'.format(Section.section_name), 'warning')
        return redirect(url_for('section.sections'))
    
    form = SectionForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            #image_filename = ""
            #if request.files['image']:
                #image_filename = images.save(request.files['image'])
            appt = Section(#image=image_filename,
                    #owner_organisation=org.org_name,
                    #organisation_id=org.id,
                section_name = form.section_name.data,
                public = form.public.data
                           )
            db.session.add(appt)
            db.session.commit()
            flash('Section {} successfully created'.format(appt.section_name), 'success')
            return redirect(url_for('section.sections'))
    return render_template('section/add_section.html', form=form, org=org)


@section.route('/<int:section_id>/section/edit', methods=['GET', 'POST'])
#@login_required
def edit_section(section_id):
    org = Organisation.query.get(1)
    settings = Section.query.filter_by(id=section_id).first_or_404()
    photo = Section.query.filter_by(id=section_id).first_or_404()
    url = images.url(photo.image)
    form = SectionForm(obj=settings)
    if request.method == 'POST' and 'image' in request.files:
        image = images.save(request.files['image'])
        appt = Section(image=image,
                      #owner_organisation=org.org_name,
                      #organisation_id=org.id,
                    section_name = form.section_name.data
                    #section_title = form.section_title.data
                    #section_description = form.section_description.data
                          )
        db.session.add(appt)
        db.session.commit()
    #if request.method == 'POST' and 'image' in request.files:
       # image = images.save(request.files['image'])
        #form.populate_obj(settings)
        #db.session.add(settings)
        #db.session.commit()
        flash('Data edited!', 'success')
        return redirect(url_for('section.sections'))
    else:
        flash('Error! Data was not added.', 'error')
    return render_template('section/edit_section.html', form=form, url=url)


@section.route('/section', defaults={'page': 1}, methods=['GET'])
@section.route('/section/<int:page>', methods=['GET'])
#@login_required
#@admin_required
def sections(page):
    sections = Section.query.paginate(page, per_page=100)
    return render_template('section/browse.html', sections=sections)


@section.route('/section/<int:section_id>/_delete', methods=['GET'])
@login_required
@admin_required
def delete_section(section_id):
    section = Section.query.filter_by(id=section_id).first()
    db.session.delete(section)
    db.session.commit()
    flash('Successfully deleted a section member.', 'success')
    return redirect(url_for('section.sections'))


@section.route('/<int:section_id>/<section_name>/content/add', methods=['GET', 'POST'])
@login_required
@admin_required
def add_content(section_id, section_name):
    
    content_exist = Content.query.filter_by(section_id=section_id).count()
    if content_exist >= 1:
        flash('Contents for {} already exist'.format(section_name), 'warning')
        return redirect(url_for('section.add_section'))
    
    settings = Section.query.filter_by(id=section_id, section_name=section_name).first()
    
    form = ContentForm(obj=settings)
    if request.method == 'POST':
        if form.validate_on_submit():
            appt = Content(section_id=section_id)
            form.populate_obj(appt)
            db.session.add(appt)
            db.session.commit()
            flash('Contents for {} successfully created'.format(appt.section_name), 'success')
            return redirect(url_for('section.contents'))
    return render_template('section/add_content.html', form=form)


@section.route('/content', defaults={'page': 1}, methods=['GET'])
@section.route('/content/<int:page>', methods=['GET'])
#@login_required
#@admin_required
def contents(page):
    contents = Content.query.paginate(page, per_page=100)
    section = Section.query.all()
    return render_template('section/contents.html', contents=contents, section=section)

@section.route('/<int:content_id>/content/edit', methods=['GET', 'POST'])
#@login_required
def edit_content(content_id):
    settings = Content.query.filter_by(id=content_id).first_or_404()
    photo = Content.query.filter_by(id=content_id).first_or_404()
    url = images.url(photo.image)
    form = ContentForm(obj=settings)
    if request.method == 'POST' and 'image' in request.files:
        image = images.save(request.files['image'])
        appt = Content(image=image,
                      #owner_organisation=org.org_name,
                      #organisation_id=org.id,
                    sections = form.sections.data,
                    title = form.title.data,
                    video = form.video.data,
                    text = form.text.data,
                    description = form.description.data
                          )
        db.session.add(appt)
        db.session.commit()
    #if request.method == 'POST' and 'image' in request.files:
       # image = images.save(request.files['image'])
        #form.populate_obj(settings)
        #db.session.add(settings)
        #db.session.commit()
        flash('Data edited!', 'success')
        return redirect(url_for('section.contents'))
    else:
        flash('Error! Data was not added.', 'error')
    return render_template('section/edit_content.html', form=form, url=url)

@section.route('/content/<int:content_id>/_delete', methods=['GET'])
@login_required
@admin_required
def delete_content(content_id):
    content = Content.query.filter_by(id=content_id).first()
    db.session.delete(content)
    db.session.commit()
    flash('Successfully deleted a section member.', 'success')
    return redirect(url_for('section.contents'))

##@section.route('/section/add', methods=['Get', 'POST'])
##@section.route('/add/section', methods=['Get', 'POST'])
###@login_required
##def add_section():
##    org = Organisation.query.get(1)
##    form = SectionForm()
##
##    if request.method == 'POST' and 'image' in request.files:
##        image = images.save(request.files['image'])
##        appt = Section(image=image,
##                    #owner_organisation=org.org_name,
##                    #organisation_id=org.id,
##
##                    section_name = form.section_name.data,
##                    section_title = form.section_title.data,
##                    section_description = form.section_description.data
##                          )
##        db.session.add(appt)
##        db.session.commit()
##        flash('Section added!', 'success')
##        return redirect(url_for('section.sections'))
##    return render_template('section/add_section.html', form=form, org=org)

flask-base/app/templates/section/add_content.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}


{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <a class="ui basic compact button" href="{{ url_for('admin.frontend_dashboard') }}">
                <i class="caret left icon"></i>
                Back to Frontend Dashboard
            </a>
            <h2 class="ui header">
                Add contents to web page sections
                <div class="sub header">Add a new content to existing sections</div>
                <div class="sub header">Note: You don't have to fill out all the fields if you don't have information for them. You can leave some fields blank</div>
            </h2>

            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-email']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}
            <div class="two fields">
                {{ f.render_form_field(form.section_name) }}
                {{ f.render_form_field(form.title) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.text) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.description) }}
            </div>
            <div class="field">
                {# f.render_form_field(form.image) #}
            </div>
            <div class="field">
                {{ f.render_form_field(form.video) }}
            </div>
            {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
            {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
            {{ f.form_message(flashes['info'], header='Information', class='info') }}
            {{ f.form_message(flashes['success'], header='Success!', class='success') }}

            {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                {{ f.render_form_field(field) }}
            {% endfor %}

            {{ f.end_form() }}

        </div>
    </div>
{% endblock %}

flask-base/app/templates/section/add_section.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}


{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <a class="ui basic compact button" href="{{ url_for('admin.frontend_dashboard') }}">
                <i class="caret left icon"></i>
                Back to Frontend Dashboard
            </a>
            <h2 class="ui header">
                Add a section Landing FrontPage
                <div class="sub header">Add a new section to the landing page</div>
            </h2>

            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-email']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}
            <div class="field">
                {{ f.render_form_field(form.section_name) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.public) }}
            </div>
            <div class="field">
                {# f.render_form_field(form.section_description) #}
            </div>
            <div class="field">
                {# f.render_form_field(form.image) #}
            </div>

            {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
            {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
            {{ f.form_message(flashes['info'], header='Information', class='info') }}
            {{ f.form_message(flashes['success'], header='Success!', class='success') }}

            {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                {{ f.render_form_field(field) }}
            {% endfor %}

            {{ f.end_form() }}

        </div>
    </div>
{% endblock %}

flask-base/app/templates/section/browse.html
{% extends 'layouts/base.html' %}

{% block content %}

        <div class="ui container">
            <a class="ui basic compact button" href="{{ url_for('admin.frontend_dashboard') }}">
                <i class="caret left icon"></i>
                Back to Frontend dashboard
            </a>  
 	
		<a class="ui right floated green button" href="{{ url_for('section.add_section') }}">
                <i class="caret right icon"></i>
                Add New Section
            </a> 
            <h2 class="ui header">
               Manage Sections Added 
                <div class="sub header">
                    View and manage sections shown on the front landing page.
                </div>
            </h2>

            {# Use overflow-x: scroll so that mobile views don't freak out
             # when the table is too wide #}
            <div style="overflow-x: scroll;">
                <table class="ui searchable sortable unstackable selectable celled table">
                    <thead>
                    <tr>
                        <th>Section Name</th>
                        <th>Public</th>
                        <!---<th>Section Title</th>
                        <th>Section Description</th>
                        <th>Image</th>--->
                        <th class="sorted ascending">Created At</th>
                        <th>Last Update</th>
                        <th>Add Content</th>
                        <th>Delete</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for section in sections.items | sort(attribute='created_at') %}
                        <tr>
                            <td>{{ section.section_name[:50] }}...</td>
                            <td>{{ section.public }}</td>
                            <!---<td>{# section.section_title #}</td>
                            <td>{# section.section_description #}</td>
                            <td>{# section.image #}</td>--->
                            <td>{{ section.created_at }}</td>
                            <td>{{ section.updated_at }}</td>
							<td><a class="ui blue left floated button" style="margin-top: 1px" href="{{ url_for('section.add_content', section_id=section.id, section_name=section.section_name) }}">Add content</a></td>

                            <td>
                                <a class="ui red left floated button" style="margin-top: 1px"
                                   href="/section/{{section.id}}/_delete">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

            <br>
            <br>
            <br>
            <div class="ui centered grid ">
                <div class="ui pagination menu">
                    {% for page in sections.iter_pages() %}
                        {% if page %}
                            {% if page != sections.page %}
                                <a class="item" href="{{ url_for('section.sections', page=page) }}">
                                    {{ page }}
                                </a>
                            {% else %}
                                <a class="item active">
                                    {{ page }}
                                </a>
                            {% endif %}
                        {% else %}
                            <div class="disabled item">
                                ...
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>



        <form method="POST" action="{{ url_for('section.delete_section', section_id=0) }}" id="delete-section-form">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        </form>
    </div>

{% endblock %}

{% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script>
        function confirmDeleteTeam(section_id){
            swal({
                title: "Are you sure?",
                text: "Once deleted, you will not be able to recover this section",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        let form = $("#delete-section-form");
                        form.attr('action', "{{ url_for('section.delete_section', section_id=0) }}".replace('0',section_id));
                        form.submit();
                    } else {
                        return false;
                    }
                });
            return false;
        }
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#search-users').keyup(function () {
                var searchText = $(this).val();
                if (searchText.length > 0) {
                    $('tbody td:icontains(' + searchText + ')').addClass('positive');
                    $('td.positive').not(':icontains(' + searchText + ')').removeClass('positive');
                    $('tbody td').not(':icontains(' + searchText + ')').closest('tr').addClass('hidden').hide();
                    $('tr.hidden:icontains(' + searchText + ')').removeClass('hidden').show();
                } else {
                    $('td.positive').removeClass('positive');
                    $('tr.hidden').removeClass('hidden').show();
                }
            });

            $('#select-role').dropdown({
                onChange: function (value, text, $selectedItem) {
                    $('td.user.role:contains(' + value + ')').closest('tr').removeClass('hidden').show();
                    $('td.user.role').not(':contains(' + value + ')').closest('tr').addClass('hidden').hide();
                }
            });
        });
    </script>
{% endblock %}

flask-base/app/templates/section/contents.html
{% extends 'layouts/base.html' %}

{% block content %}

        <div class="ui container">
            <a class="ui basic compact button" href="{{ url_for('admin.frontend_dashboard') }}">
                <i class="caret left icon"></i>
                Back to Frontend dashboard
            </a>  
 	
		<a class="ui right floated green button" href="{{ url_for('section.add_section') }}">
                <i class="caret right icon"></i>
                Add New Content
            </a> 
            <h2 class="ui header">
               Manage Contents Added 
                <div class="sub header">
                    View and manage contents shown on the front landing page.
                </div>
            </h2>

            {# Use overflow-x: scroll so that mobile views don't freak out
             # when the table is too wide #}
            <div style="overflow-x: scroll;">
                <table class="ui searchable sortable unstackable selectable celled table">
                    <thead>
                    <tr>
                        <th>Section Name</th>
                        <th>Content Title</th>
                        <th>Content Description</th>
                        <th>Image</th>
                       <th>Text</th>
                       <th>Video</th>
                        <th class="sorted ascending">Created At</th>
                        <th>Last Update</th>
                        <th>Delete</th>
                    </tr>
                    </thead>
					
                    <tbody>
                    {% for content in contents.items | sort(attribute='created_at') %}
                        <tr>
                            <td>{{ content.section_name }}</td>
                            <td>{{ content.title }}</td>
                            <td>{{ content.description }}</td>
                            <td>{{ content.image }}</td>
                            <td>{{ content.text }}</td>
                            <td>{{ content.video }}</td>
                            <td>{{ content.created_at }}</td>
                            <td>{{ content.updated_at }}</td>
                            <td>
                                <a class="ui red left floated button" style="margin-top: 1px"
                                   href="/content/{{content.id}}/_delete">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

            <br>
            <br>
            <br>
            <div class="ui centered grid ">
                <div class="ui pagination menu">
                    {% for page in contents.iter_pages() %}
                        {% if page %}
                            {% if page != contents.page %}
                                <a class="item" href="{{ url_for('section.contents', page=page) }}">
                                    {{ page }}
                                </a>
                            {% else %}
                                <a class="item active">
                                    {{ page }}
                                </a>
                            {% endif %}
                        {% else %}
                            <div class="disabled item">
                                ...
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>



        <form method="POST" action="{{ url_for('section.delete_content', content_id=0) }}" id="delete-content-form">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        </form>
    </div>

{% endblock %}

{% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script>
        function confirmDeleteContent(content_id){
            swal({
                title: "Are you sure?",
                text: "Once deleted, you will not be able to recover this content",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        let form = $("#delete-content-form");
                        form.attr('action', "{{ url_for('content.delete_content', content_id=0) }}".replace('0',content_id));
                        form.submit();
                    } else {
                        return false;
                    }
                });
            return false;
        }
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#search-users').keyup(function () {
                var searchText = $(this).val();
                if (searchText.length > 0) {
                    $('tbody td:icontains(' + searchText + ')').addClass('positive');
                    $('td.positive').not(':icontains(' + searchText + ')').removeClass('positive');
                    $('tbody td').not(':icontains(' + searchText + ')').closest('tr').addClass('hidden').hide();
                    $('tr.hidden:icontains(' + searchText + ')').removeClass('hidden').show();
                } else {
                    $('td.positive').removeClass('positive');
                    $('tr.hidden').removeClass('hidden').show();
                }
            });

            $('#select-role').dropdown({
                onChange: function (value, text, $selectedItem) {
                    $('td.user.role:contains(' + value + ')').closest('tr').removeClass('hidden').show();
                    $('td.user.role').not(':contains(' + value + ')').closest('tr').addClass('hidden').hide();
                }
            });
        });
    </script>
{% endblock %}

flask-base/app/templates/section/edit_content.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}


{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <a class="ui basic compact button" href="{{ url_for('admin.frontend_dashboard') }}">
                <i class="caret left icon"></i>
                Back to Frontend Dashboard
            </a>
            <h2 class="ui header">
                Edit Section Contents
                <div class="sub header">Edit contents</div>
            </h2>

            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-email']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}
            <div class="two fields">
                {{ f.render_form_field(form.sections) }}
                {{ f.render_form_field(form.title) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.description) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.image) }}
            </div>
                <div class="ui small image" style="flex-grow: 0">
                    <img src="{{url}}">
                </div>

            {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
            {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
            {{ f.form_message(flashes['info'], header='Information', class='info') }}
            {{ f.form_message(flashes['success'], header='Success!', class='success') }}

            {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                {{ f.render_form_field(field) }}
            {% endfor %}

            {{ f.end_form() }}

        </div>
    </div>
{% endblock %}