flask-base/app/models/event.py
from .. import db
from datetime import datetime
from logging import log
from time import time

class Event(db.Model):
    __tablename__ = 'events'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    title = db.Column(db.String)
    description = db.Column(db.Text)
    start_time= db.Column(db.DateTime)
    end_time= db.Column(db.DateTime)
    banner = db.Column(db.String, default=None, nullable=True)
    banner_displayed = db.Column(db.Boolean, default=False)
    login_required = db.Column(db.Boolean, default=False)
    video = db.Column(db.String)
    programmes = db.relationship('Programme', backref='event', lazy='dynamic')

    created_at = db.Column(db.DateTime, default=db.func.now())
    updated_at = db.Column(db.DateTime, default=db.func.now(), onupdate=db.func.now())

    def __repr__(self):
        return u'<{self.__class__.__name__}: {self.id}>'.format(self=self)

flask-base/app/blueprints/event/forms.py
from flask_ckeditor import CKEditorField
from flask_uploads import UploadSet, IMAGES
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import ValidationError
from wtforms.ext.sqlalchemy.fields import QuerySelectField, QuerySelectMultipleField
from wtforms.fields import (
    PasswordField,
    StringField,
    SubmitField,
    SelectField,
    IntegerField,
    DecimalField,
    FloatField,
    FileField,
    BooleanField,
    MultipleFileField,
    TextAreaField
    
)
from wtforms.fields.html5 import EmailField, DateField, DateTimeLocalField
from wtforms.validators import (
    Email,
    EqualTo,
    InputRequired,
    Length,
)
from wtforms.validators import Email, EqualTo, InputRequired, Length, Optional
from wtforms_alchemy import Unique, ModelForm, model_form_factory
from app.models import *


images = UploadSet('images', IMAGES)
BaseModelForm = model_form_factory(FlaskForm)

class EventForm(FlaskForm):
    name = StringField('Event Name E.g Sunday Service')
    title = StringField('Event Title or Slogan')
    description = TextAreaField('Event Description')
    start_time = DateTimeLocalField('StartDate & Time:', format='%Y-%m-%dT%H:%M')
    end_time = DateTimeLocalField('EndDate & Time:', format='%Y-%m-%dT%H:%M')
    video = FileField('Video', validators=[FileRequired()])
    image = FileField('Welcome banner Image to be displayed', validators=[Optional(), FileAllowed(images, 'Images only!')])
    banner_displayed = BooleanField("Display banner ?")
    login_required = BooleanField("Registration Required ?")
    submit = SubmitField('Submit')

flask-base/app/blueprints/event/__init__.py
from app.blueprints.event import errors  # noqa
from app.blueprints.event.views import * # noqa

flask-base/app/blueprints/event/views.py
import json
import os
from flask import render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from flask_uploads import UploadSet, IMAGES
from flask_wtf.file import FileAllowed
from wtforms import Flags

from app import db
from app.blueprints.event.forms import EventForm
from app.decorators import admin_required
from app.models import *

from flask import Blueprint, render_template

from app.models import EditableHTML

event = Blueprint('event', __name__)
images = UploadSet('images', IMAGES)
photos = UploadSet('photos', IMAGES)


@event.app_errorhandler(500)
def internal_server_error(_):
    return render_template('errors/500.html'), 500


@event.route('/event/add', methods=['Get', 'POST'])
@event.route('/add/event', methods=['Get', 'POST'])
#@login_required
def add_event():
    org = Organisation.query.get(1)
    form = EventForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            image_filename = ""
            if request.files['image']:
                image_filename = images.save(request.files['image'])
            video_filename = request.files['video']
            if video_filename.filename != '':
            #if request.files['video']:
                video_filename.save(os.path.join(current_app.config['UPLOADED_FILES_DEST'], video_filename.filename))
     
            appt = Event(banner=image_filename,
                name = form.name.data,
                title = form.title.data,
                video = video_filename.filename,
                description = form.description.data,
                start_time = form.start_time.data,
                end_time = form.end_time.data,
                banner_displayed = form.banner_displayed.data,   
                login_required = form.login_required.data
                            )
            db.session.add(appt)
            db.session.commit()
            flash('event {} successfully created'.format(appt.name), 'success')
            return redirect(url_for('event.events'))
    return render_template('event/add_event.html', form=form)


@event.route('/<int:event_id>/event/edit', methods=['GET', 'POST'])
#@login_required
def edit_event(event_id):
    org = Organisation.query.get(1)
    settings = Event.query.filter_by(id=event_id).first_or_404()
    photo = Event.query.filter_by(id=event_id).first_or_404()
    url = images.url(photo.image)
    form = EventForm(obj=settings)
    if request.method == 'POST' and 'image' in request.files:
        image = images.save(request.files['image'])
        appt = Event(image=image,
                      #owner_organisation=org.org_name,
                      #organisation_id=org.id,
                    event_name = form.name.data,
                    event_title = form.title.data,
                    event_description = form.description.data
                          )
        db.session.add(appt)
        db.session.commit()
    #if request.method == 'POST' and 'image' in request.files:
       # image = images.save(request.files['image'])
        #form.populate_obj(settings)
        #db.session.add(settings)
        #db.session.commit()
        flash('Data edited!', 'success')
        return redirect(url_for('event.events'))
    else:
        flash('Error! Data was not added.', 'error')
    return render_template('event/edit_event.html', form=form, url=url)


@event.route('/event', defaults={'page': 1}, methods=['GET'])
@event.route('/event/<int:page>', methods=['GET'])
#@login_required
#@admin_required
def events(page):
    events = Event.query.paginate(page, per_page=100)
    return render_template('event/browse.html', events=events)


@event.route('/event/<int:event_id>/_delete', methods=['GET'])
@login_required
@admin_required
def delete_event(event_id):
    event = Event.query.filter_by(id=event_id).first()
    db.session.delete(event)
    db.session.commit()
    flash('Successfully deleted a event member.', 'success')
    return redirect(url_for('event.events'))



##@event.route('/event/add', methods=['Get', 'POST'])
##@event.route('/add/event', methods=['Get', 'POST'])
###@login_required
##def add_event():
##    org = Organisation.query.get(1)
##    form = EventForm()
##
##    if request.method == 'POST' and 'image' in request.files:
##        image = images.save(request.files['image'])
##        appt = Event(image=image,
##                    #owner_organisation=org.org_name,
##                    #organisation_id=org.id,
##
##                    event_name = form.event_name.data,
##                    event_title = form.event_title.data,
##                    event_description = form.event_description.data
##                          )
##        db.session.add(appt)
##        db.session.commit()
##        flash('Event added!', 'success')
##        return redirect(url_for('event.events'))
##    return render_template('event/add_event.html', form=form, org=org)

flask-base/app/templates/event/add_event.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}


{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <a class="ui basic compact button" href="{{ url_for('admin.event_dashboard') }}">
                <i class="caret left icon"></i>
                Back to Event Dashboard
            </a>
            <h2 class="ui header">
                Add a event 
                <div class="sub header">Add a new event </div>
            </h2>

            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-email']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}
            <div class="two fields">
                {{ f.render_form_field(form.name) }}
                {{ f.render_form_field(form.title) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.description) }}
            </div>
			
            <div class="two fields">
                {{ f.render_form_field(form.start_time) }}
                {{ f.render_form_field(form.end_time) }}
            </div>
            <div class="two fields">
                {{ f.render_form_field(form.image) }}
                {{ f.render_form_field(form.banner_displayed) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.video) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.login_required) }}
            </div>
            {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
            {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
            {{ f.form_message(flashes['info'], header='Information', class='info') }}
            {{ f.form_message(flashes['success'], header='Success!', class='success') }}

            {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                {{ f.render_form_field(field) }}
            {% endfor %}

            {{ f.end_form() }}

        </div>
    </div>
{% endblock %}

flask-base/app/templates/event/browse.html
{% extends 'layouts/base.html' %}

{% block content %}

        <div class="ui container">
            <a class="ui basic compact button" href="{{ url_for('admin.event_dashboard') }}">
                <i class="caret left icon"></i>
                Back to Event dashboard
            </a>  
 	
		<a class="ui right floated green button" href="{{ url_for('event.add_event') }}">
                <i class="caret right icon"></i>
                Add New Event
            </a> 
            <h2 class="ui header">
               Manage Events Added 
                <div class="sub header">
                    View and manage events shown on the front landing page.
                </div>
            </h2>

            {# Use overflow-x: scroll so that mobile views don't freak out
             # when the table is too wide #}
            <div style="overflow-x: scroll;">
                <table class="ui searchable sortable unstackable selectable celled table">
                    <thead>
                    <tr>
                        <th>Event Name</th>
                        <th>Event Title</th>
                        <th>Description</th>
                        <th>Banner</th>
                        <th>Banner Displayed</th>
						<th>Video</th>
                        <th>Start Time</th>
						<th>End Time</th>
						<th>Login Required</th>
                        <th class="sorted ascending">Created At</th>
                        <th>Last Update</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for event in events.items | sort(attribute='created_at') %}
                        <tr>
                            <td>{{ event.name }}...</td>
                            <td>{{ event.title }}</td>
                            <td>{{ event.description }}</td>
                            <td>{{ event.banner }}</td>
                            <td>{{ event.banner_displayed }}</td>
                            <td>{{ event.video }}</td>
                            <td>{{ event.start_time }}</td>
                            <td>{{ event.end_time }}</td>
                            <td>{{ event.login_required }}</td>
                            <td>{{ event.created_at }}</td>
                            <td>{{ event.updated_at }}</td>
                            <td>
                                <a class="ui blue left floated button" style="margin-top: 1px" href="{{ url_for('event.edit_event', event_id=event.id) }}">Edit</a>							
							</td>
                            <td>
                                <a class="ui red left floated button" style="margin-top: 1px"
                                   href="/event/{{event.id}}/_delete">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

            <br>
            <br>
            <br>
            <div class="ui centered grid ">
                <div class="ui pagination menu">
                    {% for page in events.iter_pages() %}
                        {% if page %}
                            {% if page != events.page %}
                                <a class="item" href="{{ url_for('event.events', page=page) }}">
                                    {{ page }}
                                </a>
                            {% else %}
                                <a class="item active">
                                    {{ page }}
                                </a>
                            {% endif %}
                        {% else %}
                            <div class="disabled item">
                                ...
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>



        <form method="POST" action="{{ url_for('event.delete_event', event_id=0) }}" id="delete-event-form">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        </form>
    </div>

{% endblock %}

{% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script>
        function confirmDeleteEvent(event_id){
            swal({
                title: "Are you sure?",
                text: "Once deleted, you will not be able to recover this event",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        let form = $("#delete-event-form");
                        form.attr('action', "{{ url_for('event.delete_event', event_id=0) }}".replace('0',event_id));
                        form.submit();
                    } else {
                        return false;
                    }
                });
            return false;
        }
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#search-users').keyup(function () {
                var searchText = $(this).val();
                if (searchText.length > 0) {
                    $('tbody td:icontains(' + searchText + ')').addClass('positive');
                    $('td.positive').not(':icontains(' + searchText + ')').removeClass('positive');
                    $('tbody td').not(':icontains(' + searchText + ')').closest('tr').addClass('hidden').hide();
                    $('tr.hidden:icontains(' + searchText + ')').removeClass('hidden').show();
                } else {
                    $('td.positive').removeClass('positive');
                    $('tr.hidden').removeClass('hidden').show();
                }
            });

            $('#select-role').dropdown({
                onChange: function (value, text, $selectedItem) {
                    $('td.user.role:contains(' + value + ')').closest('tr').removeClass('hidden').show();
                    $('td.user.role').not(':contains(' + value + ')').closest('tr').addClass('hidden').hide();
                }
            });
        });
    </script>
{% endblock %}

flask-base/app/templates/event/edit_event.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}


{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <a class="ui basic compact button" href="{{ url_for('admin.Church_dashboard') }}">
                <i class="caret left icon"></i>
                Back to Church Dashboard
            </a>
            <h2 class="ui header">
                Edit Event Details
                <div class="sub header">Edit details</div>
            </h2>

            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-email']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}
            <div class="two fields">
                {{ f.render_form_field(form.event_name) }}
                {{ f.render_form_field(form.event_title) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.event_description) }}
            </div>
            <div class="field">
                {{ f.render_form_field(form.image) }}
            </div>
                <div class="ui small image" style="flex-grow: 0">
                    <img src="{{url}}">
                </div>

            {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
            {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
            {{ f.form_message(flashes['info'], header='Information', class='info') }}
            {{ f.form_message(flashes['success'], header='Success!', class='success') }}

            {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                {{ f.render_form_field(field) }}
            {% endfor %}

            {{ f.end_form() }}

        </div>
    </div>
{% endblock %}

flask-base/app/templates/event/event_settings_dashboard.html
{% extends 'layouts/base.html' %}

{% macro dashboard_option(title, endpoint, description=None, icon=None) %}
    <a class="column" href="{{ url_for(endpoint) }}">
        <div class="ui padded segment">
            <h3 class="ui header">
                {% if icon is not none %}
                    <i class="{{ icon }}"></i>
                {% endif %}
                <div class="content">
                    {{ title }}
                    {% if description is not none %}
                        <div class="sub header">
                            {{ description }}
                        </div>
                    {% endif %}
                </div>
            </h3>
        </div>
    </a>
{% endmacro %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
			<h2 class="ui center aligned icon header">
			  <i class="settings icon"></i>
			 Event Programmes Management Dashboard
			  <div class="content">
				
				<div class="sub header">Click on these tabs to add or edit sections added to the front landing page website.</div>
			  </div>
			</h2>
            <div class="ui two column stackable grid">
                {{ dashboard_option('Add new event', 'event.add_event',
                                    description='Click to add a new event', icon='bars icon') }}	
                {{ dashboard_option('Manage events', 'event.events',
                                    description='View and manage existing events', icon='edit icon') }}	
                {{ dashboard_option('Add new programme', 'programme.add_programme',
                                    description='Click to add a new programme of events', icon='bars icon') }}	
                {{ dashboard_option('Manage programme of events', 'programme.programmes',
                                    description='View and manage existing event programmes', icon='edit icon') }}	
                {{ dashboard_option('Add or delete background banner', 'programme.banners',
                                    description='Add or edit background banner image', icon='image outline icon') }}																	
									
            </div>
        </div>
    </div>
{% endblock %}